### ISSUE TITLE
When will 1.1.0 be available on Terraform?

### ISSUE THREAD

**Issue by palmithor** [alekc/terraform-provider-auth0#18]
Hey, 

First of all I find it awesome that you've continued the work of alexkappa, this is something that should be in rapid development I feel. 

I noticed that you've already released 1.1.0 here on github, however it is not available on Terraform. Just wanted to know if you have plans for publishing it?

Thanks again for a great contribution.

**Comment by alekc** [comment]
Thx. I am trying to release it now actually, just run into some issues with pipelines (my previous tenancy trial expired and. as consequence pipelines are failing because I cannot create some infra objects <.<). 

As soon as the pipeline is fixed I will be able to release it, hopefully somewhat in the next couple of hours.

**Comment by alekc** [comment]
@palmithor `v1.1.1` has been released and available on terraform registry. After the sync v1.1.0 is available on terraform as well. 

Closing
